### ISSUE TITLE
Errors don't return status codes

### ISSUE THREAD

**Issue by iceeburr** [Sleitnick/rbxcloud#43]
When it errors for whatever reason, it doesn't return an error status, therefore using it inside GitHub Actions for example, the process continues running.
![image](https://github.com/Sleitnick/rbxcloud/assets/85520957/e4905c9e-07cf-4cf2-853b-6b786570e09d)
*The action failed from another error not related to this.*

I found a workaround by making a powershell script to match a string pattern from the output. While it is a working, it should properly return error statuses. This same particular issue applies to some other well known tools like the wally package manager for example.
```ps1
$rbxcloudOutput = rbxcloud experience publish -f roblox-video-codec.rbxl -p ${env:PLACE_ID} -u ${env:GAME_ID} -t published -a ${env:DEPLOY_API_KEY} 2>&1

if ($rbxcloudOutput -notlike "*published * with version number*") {
    Write-Host "::error::$rbxcloudOutput"
    exit 1
}
```
<details closed>
<summary>You need to make sure to add the env variables to your actual workflow:</summary>

```yml
env:
  ASSET_ID: ${{ vars.ASSET_ID }}
  PLACE_ID: ${{ vars.PLACE_ID }}
  GAME_ID: ${{ vars.GAME_ID }}
  DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
  WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}
```

</details>

Example of how it should look and act like (used the script):

![image](https://github.com/Sleitnick/rbxcloud/assets/85520957/caac75e0-e8e2-45d7-ace1-491b2cfd683e)
